name: vhs

env: 
  EXAMPLE_NAME: deeper

permissions:
  contents: write

on:
  push:
    paths:
      - "**/*.tape"

defaults:
  run:
    working-directory: ./examples/deeper

jobs:
  vhs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21.6
      - uses: charmbracelet/vhs-action@v2
        env:
          TERM: xterm-256color
        with:
          path: "./demo.tape"
      - uses: stefanzweifel/git-auto-commit-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit_message: Generated deeper demo VHS GIF
          branch: main
          commit_user_name: vhs-action 📼
          commit_user_email: actions@github.com
          commit_author: vhs-action 📼 <actions@github.com>
          file_pattern: "*.gif"

  