name: vhs

permissions:
  contents: write

on:
  push:
    paths:
      - "**/*.tape"

jobs:
  vhs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.0

      - name: Build Examples
        run: go build -o ./bin/deeper ./examples/deeper/*.go && go build -o ./bin/simple ./examples/simple/*.go && go build -o ./bin/hosted ./examples/hosted/*.go

      - name: Create deeper demo GIF
        uses: charmbracelet/vhs-action@v2
        env:
          TERM: xterm-256color
        with:
          path: ./examples/deeper/demo.tape
      
      - name: Move deeper demo GIF to examples/deeper
        run: mv demo.gif examples/deeper/demo.gif 

      - name: Create simple demo GIF
        uses: charmbracelet/vhs-action@v2
        env:
          TERM: xterm-256color
        with:
          path: ./examples/simple/demo.tape
      
      - name: Move simple demo GIF to examples/simple
        run: mv demo.gif examples/simple/demo.gif 

      - name: Create hosted demo GIF
        uses: charmbracelet/vhs-action@v2
        env:
          TERM: xterm-256color
        with:
          path: ./examples/hosted/demo.tape
      
      - name: Move hosted demo GIF to examples/hosted
        run: mv demo.gif examples/hosted/demo.gif 

      - name: Commit and push demo.gif
        uses: stefanzweifel/git-auto-commit-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit_message: Generated demo VHS GIFs
          branch: main
          commit_user_name: vhs-action 📼
          commit_user_email: actions@github.com
          commit_author: vhs-action 📼 <actions@github.com>
          file_pattern: "*.gif"
